### ISSUE TITLE
Issue with placing pixels

### ISSUE THREAD

**Issue by spencer-scw** [anaga-dev/pixel#10]
I'm not sure how tough this will be to reproduce, but I tried this out after seeing it on Reddit and the program is placing pixels down and to the right of where I click unless I click in the very top left corner of the pixel. I'm on Firefox on Windows and I'm editing an 8x8 canvas if that helps. In general, the behavior of placing pixels doesn't match where I feel like I'm clicking.

**Comment by mekanoide** [comment]
It's a problem we're working on. It'll be fixed really soon!

Thank you for your feedback!

**Comment by mekanoide** [comment]
Fixed!!!
